version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      #- aws codeartifact login --tool npm --domain zechak --repository reactify-zk # --region eu-central-1
      - START=$(date +%s)
      - yarn install
      - END=$(date +%s)
      - DIFF=$(( $END - $START ))
      - echo "It took $DIFF seconds for yarn install"
  build:
    commands:
      - echo "inside build" 
# cache:
#   paths:
#     - 'node_modules/**/*'
#     - '.next/cache/**/*'

